twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        app_name: 'RGAA Audit'

when@dev:
    twig:
        markdown:
            enabled: true

when@prod:
    twig:
        markdown:
            enabled: true

when@test:
    twig:
        strict_variables: true
